### ISSUE TITLE
Add mrcnn as a dependency instead of copying the code

### ISSUE THREAD

**Issue by wrznr** [mjenckel/ocrd_anybaseocr#13]
https://github.com/matterport/Mask_RCNN/tree/master/mrcnn is used in your repository. Why do you include it by copying? The module is pip-installable. Alternatively, a reference to the GitHub repository could be added.

**Comment by khurramHashmi** [comment]
We have done some changes to the original scripts present in mrcnn folder. Specifically, the config.py file has a lot of changes. Since we are using Tensorflow 2.0 now, so we had to change some functions in model.py as well. Although, unnecessary scripts that are not required during inference could be deleted.

**Comment by wrznr** [comment]
@khurramHashmi Great work. Getting mrcnn running with Tensorflow 2.0 is a great achievement (cf. https://github.com/matterport/Mask_RCNN/pull/1896 and the PRs referenced there)! Please consider to propose your modifications for the upstream mrcnn. Many, many people would benefit from that.
