### ISSUE TITLE
Licensing of tiseg

### ISSUE THREAD

**Issue by kba** [mjenckel/ocrd_anybaseocr#2]
https://github.com/mjenckel/LAYoutERkennung/blob/master/ocrd_anybaseocr/cli/ocrd_anybaseocr_tiseg.py#L7-L9
> #The anyBaseOCR-tiseg is licensed under the "OpenContent License". While using/refering this work, always add the reference of the following paper: 

That is contradictory to the Apache 2.0 license.

**Comment by n00blet** [comment]
Sorry, the license for anyBaseOCR-tiseg will be discussed internally in DFKI and will be updated.

**Comment by wrznr** [comment]
Please also discuss the license of https://github.com/mjenckel/LAYoutERkennung/blob/master/ocrd_anybaseocr/src/datagenerator.py which is right now BSD-3. The code seems to be transferred from https://github.com/kratzert/finetune_alexnet_with_tensorflow. Maybe it is even possible to add this repo as a dependency instead of duplicating the code?

**Comment by wrznr** [comment]
The same seems to hold for https://github.com/mjenckel/LAYoutERkennung/blob/master/ocrd_anybaseocr/src/finetune.py . You may want to add a reverence to @kratzert.

**Comment by mjenckel** [comment]
We are aware of the licensing issue with both [https://github.com/mjenckel/LAYoutERkennung/blob/master](https://github.com/mjenckel/LAYoutERkennung/blob/master) and [https://github.com/mjenckel/LAYoutERkennung/blob/master/ocrd_anybaseocr/src/finetune.py](https://github.com/mjenckel/LAYoutERkennung/blob/master/ocrd_anybaseocr/src/finetune.py). 

They are currently used by the block-classification module. However, we have not tried to adapt this module to the OCR-D CLI API, because we are not sure we will actually use this code in the final version. We are currently still developing our block-segmentation code, which is a joint block-segmentation and -classification which would make the current module obsolete. 
We will remove both scripts from the repo for now and link to their original versions.

As for the tiseg code, as mentioned before, we are currently discussing internally how to change the license for the OCR-D project (DFKI is the license holder).

**Comment by kba** [comment]
> We will remove both scripts from the repo for now and link to their original versions.

Please don't break existing code, license-wise it's fine.

> which would make the current module obsolete.

So should we test the code and fix issues?

**Comment by mjenckel** [comment]
since block-classification is not in OCR-D API compatible format, testing it (and its dependencies in the /src directory) does not make a lot of sense at this point.
we are considering moving this part of the code into the dev branch to reduce confusion

**Comment by n00blet** [comment]
The licensing of tiseg has been changed to Apache 2.0. 
@mjenckel can provide more clarification regarding the license if required.
