### ISSUE TITLE
Overwrite existing files in OCR-D-IMG-BIN 

### ISSUE THREAD

**Issue by VolkerHartmann** [mjenckel/ocrd_anybaseocr#25]
The binarizing overwrites existing files in OCR-D-IMG-BIN without any warning.
There should at least a warning in the documentation. Is there any possibility to define an
other output group for the images?

**Comment by mjenckel** [comment]
currently we do no checks for existing alternative images in any of the modules. I agree that it makes sense to give a warning, but I wonder if it shouldnt be done by the API so a general warning is given if an image is overwritten. @kba 
the image output group can be changed through the output file group:
`self.page_grp, self.image_grp = self.output_file_grp.split(',')`
otherwise it will fall back to the default

**Comment by VolkerHartmann** [comment]
Documentation, at least for binarization, is not sufficient. It does not become clear that 2 output groups will be created. Also the ocrd-tool.json mentions only one output group.

**Comment by mahmed1995** [comment]
Added a parameter for overwriting. 
b936028
