### ISSUE TITLE
Improve documentation for dewarp

### ISSUE THREAD

**Issue by VolkerHartmann** [mjenckel/ocrd_anybaseocr#40]
Requirements: 
Installation of pix2pixHD 
pip3 install torch torchvision
 pip install dominate
parameter model_name seems to be ignored
set parameter for pix2pixHD

**Comment by VolkerHartmann** [comment]
Still got an error:
  File "/home/user/ocrd/python/pix2pixHD/models/pix2pixHD_model.py", line 58, in initialize
    self.load_network(self.netG, 'G', opt.which_epoch, pretrained_path)            
   File "/home/user/ocrd/python/pix2pixHD/models/base_model.py", line 58, in load_network
    raise('Generator must exist!')

Please provide an example how to configure dewarper correct.
Also a link inside the README.md to the second README.md would be helpful.

**Comment by VolkerHartmann** [comment]
typo in ocrd-anybaseocr-block-segmenter -> ocrd-anybaseocr-block-segmentation

**Comment by bertsky** [comment]
The packaging of this module (and its documentation) is a **nightmare**:

> Installation of pix2pixHD

Since there's no release on PyPI, this literally means cloning https://github.com/NVIDIA/pix2pixHD
somewhere, and creating a `checkpoints` subdirectory for it, and then _passing the absolute pathname of the clone to the `pix2pixHD` parameter_

> pip3 install torch torchvision
> pip install dominate

along with a full CUDA setup

> parameter model_name seems to be ignored

No, it's not. It needs to point to the absolute pathname of the directory holding the dewarping model manually downloaded from [here](https://github.com/OCR-D/ocrd_anybaseocr/tree/master/ocrd_anybaseocr/models)

All this should have been **encapsulated** in `requirements.txt` or at least in some Makefile recipe for installation. Since there's no distribution for it, the dependency on pix2pixHD should be made a submodule. The requirement to give absolute path names (twice!) in the parameter JSON makes it impossible to ship host-independent parameter/workflow configurations. IMO the pix2pixHD path should not be a parameter at all, but resolved at install-time.

**Comment by kba** [comment]
fixed by #89
