### ISSUE TITLE
Odd default value for parameter 'parallel'

### ISSUE THREAD

**Issue by wrznr** [mjenckel/ocrd_anybaseocr#6]
In https://github.com/mjenckel/LAYoutERkennung/blob/master/ocrd_anybaseocr/ocrd-tool.json the parameter `parallel` with the description *numbers of CPUs to us* defaults to 0. Is this intended? What does that mean? Maybe GPU-based processing?

**Comment by kba** [comment]
This is used in [ocropy's gpageseg](https://github.com/tmbdev/ocropy/blob/master/ocropus-gpageseg) which is duplicated at https://github.com/mjenckel/LAYoutERkennung/blob/master/ocrd_anybaseocr/cli/anyBaseOCR-gpageseg.py. In gpageseg, `parallel < 2` means no parallelization.

Why is that script even in there as a CLI? Please consider using the code directly instead of starting a new python instance in https://github.com/mjenckel/LAYoutERkennung/blob/master/ocrd_anybaseocr/cli/ocrd_anybaseocr_textline.py#L114. And have a look at @bertsky's https://github.com/cisocrgroup/cis-ocrd-py/tree/dev/ocrd_cis/ocropy as well as https://github.com/OCR-D/ocrd_ocropy/blob/master/ocrd_ocropy/segment.py

**Comment by mjenckel** [comment]
gpageseg code has been integrated into the textline module so this parameter is no longer used
