### ISSUE TITLE
Missing Models

### ISSUE THREAD

**Issue by Schneipi** [mjenckel/ocrd_anybaseocr#98]
Since there are no models hosted on https://ocr-d-repo.scc.kit.edu, does anyone know where we can access them now? More specifically, I would want to use:

- latest_net_G.pth
- block_segmentation_weights.h5
- mapping_densenet.pickle

The URLs are outdated here: https://github.com/OCR-D/core/blob/master/ocrd/ocrd/resource_list.yml

**Comment by cneud** [comment]
@Schneipi I've added the trained models to the latest release here: 
https://github.com/OCR-D/ocrd_anybaseocr/releases/tag/v1.8.2.

**Comment by Schneipi** [comment]
@cneud thanks!

What about `mapping_densenet.pickle`? It seems to be required for `ocrd-anybaseocr-layout-analysis`. Running `ocrd resmgr download ocrd-anybaseocr-layout-analysis '*'` does not download the file and therefore `ocrd-anybaseocr-layout-analysis` throws an  `UnpicklingError`.

`seg_model.hdf5`, provided with the latest release, seems to concern `ocrd-anybaseocr-tiseg`, if I'm not mistaken.

**Comment by cneud** [comment]
@Schneipi You are right, there seem to be more required models ;)

For `mapping_densenet.pickle`, there is a Tensorflow SavedModel version for this according to [resource_list.yml](https://github.com/OCR-D/core/blob/master/ocrd/ocrd/resource_list.yml) at https://ocr-d.kba.cloud/structure_analysis.tar.gz (but which I am not sure is identical/working).

[Edit: as it turns out, `structure_analysis.h5` is just another required model, but no replacement for `mapping_densenet.pickle`.]

Unfortunately I don't have a copy of `mapping_densenet.pickle` from https://ocr-d-repo.scc.kit.edu/models/dfki/layoutAnalysis/mapping_densenet.pickle...

**Comment by kba** [comment]
We do have a copy of all the models, @tdoan2010 knows where to find them, we will find a more permanent place for them and update the `resource_list.yml` later this week, I'll keep you posted.

**Comment by tdoan2010** [comment]
Hi, yes, I have a copy of all models. And I guess here is the [`mapping_densenet.pickle`](https://s3.gwdg.de/ocr-d/models/dfki/layoutAnalysis/mapping_densenet.pickle) that you're looking for.

**Comment by cneud** [comment]
That [`mapping_densenet.pickle`](https://s3.gwdg.de/ocr-d/models/dfki/layoutAnalysis/mapping_densenet.pickle) looks suspicious as the file size is less than 1 kB...

**Comment by kba** [comment]
> That mapping_densenet.pickle looks suspicious as the file size is less than 1 kB...

IIRC this was just pickled dict mapping network outputs to region types, so the small file size tracks.

**Comment by cneud** [comment]
> IIRC this was just pickled dict mapping network outputs to region types

I see, thx. Then I will also add the file to the release.
